#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Initialization helpers for the ORCA AnyTeleop server.

Purpose
-------
This module contains setup code that should run once before the real-time
teleoperation loop begins:

- command-line argument definition;
- dex-retargeting / SingleHandDetector import setup;
- Human -> ORCA alignment selection;
- ORCA retargeter construction and initial qpos;
- fixed-wrist validation;
- OpenCV camera opening and requested capture settings.

Keeping initialization separate makes ``orca_anyteleop_server.py`` read
like the actual online pipeline instead of mixing one-time environment
construction with per-frame logic.

Behavior-preservation
---------------------
Argument names/defaults, the pinned dex-retargeting detector path, the
17-DoF check, the fixed-wrist check, zero/clamped initial qpos, and OpenCV
camera settings are intentionally the same as the successful pre-refactor
Gate 3A smoke implementation.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import cv2
import numpy as np

from dex_retargeting.retargeting_config import RetargetingConfig

from orca_vector_alignment import load_vector_alignment


DEX_EXAMPLE_DIR = (
    "/opt/dex-retargeting/"
    "example/vector_retargeting"
)

if DEX_EXAMPLE_DIR not in sys.path:
    sys.path.insert(0, DEX_EXAMPLE_DIR)

from single_hand_detector import SingleHandDetector


EXPECTED_WRIST_JOINT = (
    "R-Carpals_8d1f1041_to_"
    "TopTower-Model_4a80d30e"
)


def build_argument_parser() -> argparse.ArgumentParser:
    """Create the unchanged command-line interface for the server."""

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--config",
        required=True,
        type=Path,
    )
    parser.add_argument(
        "--alignment-config",
        type=Path,
        default=None,
        help=(
            "Optional Human-to-ORCA vector alignment YAML generated by "
            "calibrate_orca_vector_alignment.py."
        ),
    )
    parser.add_argument(
        "--camera",
        type=str,
        default="0",
    )
    parser.add_argument(
        "--host",
        type=str,
        default="127.0.0.1",
    )
    parser.add_argument(
        "--port",
        type=int,
        default=5006,
    )
    parser.add_argument(
        "--width",
        type=int,
        default=640,
    )
    parser.add_argument(
        "--height",
        type=int,
        default=480,
    )
    parser.add_argument(
        "--fps",
        type=float,
        default=30.0,
    )
    parser.add_argument(
        "--hand-type",
        choices=["Right", "Left"],
        default="Right",
    )
    parser.add_argument(
        "--selfie",
        action="store_true",
    )
    parser.add_argument(
        "--show",
        action="store_true",
    )
    parser.add_argument(
        "--wrist-position",
        type=float,
        default=0.0,
        help="Fixed ORCA wrist position in radians.",
    )
    parser.add_argument(
        "--record-path",
        type=Path,
        default=None,
        help=(
            "Optional JSONL path for research recording. Stores MediaPipe "
            "validity, human vectors, aligned vectors, and qpos."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help=(
            "Run camera, MediaPipe, vector alignment, and retargeting "
            "without transmitting UDP. Used for Gate 3A standalone "
            "validation."
        ),
    )
    parser.add_argument(
        "--duration",
        type=float,
        default=None,
        help=(
            "Optional experiment duration in seconds. If omitted, run "
            "until interrupted or q is pressed."
        ),
    )

    return parser


def initialize_alignment(args):
    """
    Load external Human -> ORCA alignment or return the identity fallback.
    """

    alignment_enabled = args.alignment_config is not None

    if alignment_enabled:
        (
            alignment_rotation,
            alignment_scale,
            alignment_det,
            alignment_orth_error,
        ) = load_vector_alignment(
            args.alignment_config
        )
    else:
        alignment_rotation = np.eye(
            3,
            dtype=np.float32,
        )
        alignment_scale = 1.0
        alignment_det = 1.0
        alignment_orth_error = 0.0

    return (
        alignment_enabled,
        alignment_rotation,
        alignment_scale,
        alignment_det,
        alignment_orth_error,
    )


def initialize_retargeting(args):
    """
    Build dex-retargeting and reproduce the ORCA initial qpos behavior.

    Returns the retargeter, optimizer, joint metadata, and the fixed wrist
    qpos required by every optimizer call.
    """

    cfg = RetargetingConfig.load_from_file(
        args.config.resolve()
    )
    retargeting = cfg.build()
    optimizer = retargeting.optimizer
    joint_names = list(retargeting.joint_names)

    robot = optimizer.robot
    joint_limits = np.asarray(
        robot.joint_limits,
        dtype=np.float32,
    )

    initial_qpos = np.zeros(
        robot.dof,
        dtype=np.float32,
    )
    initial_qpos = np.clip(
        initial_qpos,
        joint_limits[:, 0],
        joint_limits[:, 1],
    )

    wrist_index = joint_names.index(
        EXPECTED_WRIST_JOINT
    )
    initial_qpos[wrist_index] = np.clip(
        args.wrist_position,
        joint_limits[wrist_index, 0],
        joint_limits[wrist_index, 1],
    )

    retargeting.set_qpos(initial_qpos)

    fixed_joint_names = optimizer.fixed_joint_names

    if len(joint_names) != 17:
        raise RuntimeError(
            f"Expected 17 ORCA DoF, got {len(joint_names)}"
        )

    if fixed_joint_names != [EXPECTED_WRIST_JOINT]:
        raise RuntimeError(
            "Unexpected fixed joints:\n"
            f"{fixed_joint_names}"
        )

    fixed_qpos = np.asarray(
        [args.wrist_position],
        dtype=np.float32,
    )

    return (
        retargeting,
        optimizer,
        joint_names,
        joint_limits,
        initial_qpos,
        fixed_joint_names,
        fixed_qpos,
    )


def initialize_detector(args):
    """Create the pinned dex-retargeting MediaPipe hand detector."""

    return SingleHandDetector(
        hand_type=args.hand_type,
        selfie=args.selfie,
    )


def parse_camera_source(value: str):
    """Convert a digit-only camera argument to an OpenCV integer index."""

    if value.isdigit():
        return int(value)
    return value


def initialize_camera(args):
    """Open/configure the same OpenCV capture path used before refactoring."""

    camera_source = parse_camera_source(
        args.camera
    )

    cap = cv2.VideoCapture(camera_source)

    if not cap.isOpened():
        raise RuntimeError(
            f"Cannot open camera: {camera_source}"
        )

    cap.set(
        cv2.CAP_PROP_FRAME_WIDTH,
        args.width,
    )
    cap.set(
        cv2.CAP_PROP_FRAME_HEIGHT,
        args.height,
    )
    cap.set(
        cv2.CAP_PROP_FPS,
        args.fps,
    )

    return camera_source, cap
